# Generated by Django 5.2.7 on 2025-10-15 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0002_alter_categoria_nombre_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
